inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 2
