inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Metrics/LineLength:
  Max: 135

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
