branches:
  only:
    - master
language: ruby
node_js: lts/*
cache:
  bundler: true
  yarn: true
install:
  - gem install bundler
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
services:
  - mysql
before_script:
  - bundle exec rails db:drop RAILS_ENV=test
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test
script:
  - bundle exec rspec
  - yarn test
  - rails assets:precompile RAILS_ENV=production
# TODO: add deploy after ssh is setup
notifications:
  email: false
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
