version: '3.4'

services:
  ots_base:
    &rails_base
    build:
      context: .

  ots_rails:
    <<: *rails_base
    container_name: ots_rails
    ports:
      - ${APPLICATION_PORT}:3000
    working_dir: /opt/app
    depends_on:
      - ots_db
    command: "./docker/rails/boot.sh"
    env_file: .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=ots_webpacker
    volumes:
    - ./:/opt/app

  ots_webpacker:
    <<: *rails_base
    container_name: ots_webpacker
    environment:
      - NODE_ENV=${NODE_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: "./bin/webpack-dev-server"
    ports:
      - '127.0.0.1:3035:3035'
    working_dir: /opt/app
    volumes:
      - ./:/opt/app

  ots_db:
    container_name: ots_db
    image: mysql:8.0
    volumes:
      - ots_database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  ots_database:
