name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=ots_test

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
      - uses: ruby/setup-ruby@ba696adf55506673e48342a66e30f1f53cadeae0 # v1.299.0
        with:
          bundler-cache: true

      - uses: pnpm/action-setup@6b87c4621a21f802115d27ffcbfb44e28abd1387 # v5.0.0

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Runs a single command using the runners shell
      - name: Versions
        run: |
          ruby --version
          bundler --version
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Run JS tests
        run: |
          NODE_ENV=test pnpm run test

      - name: Run asset compile
        run: |
          HOST_URL=http://localhost RAILS_ENV=production SECRET_KEY_BASE=dummy SENTRY_DSN=test ./bin/rails assets:precompile

      - name: Run rspec
        run: |
          HOST_URL=http://localhost RAILS_ENV=test MYSQL_USER=root MYSQL_DATABASE="osu_tournament_stats_test" MYSQL_HOST="127.0.0.1" MYSQL_PORT=${{ job.services.mysql.ports[3306] }} SENTRY_DSN=test bundle exec rspec

      - name: Complete
        run: echo "Build complete!"
